name: hn_app
description: A new Flutter application.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  built_collection: '>=2.0.0 <5.0.0'
  built_value: ^7.1.0
  cupertino_icons: ^0.1.3
  http: ^0.12.2
  url_launcher: ^5.5.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  built_value_generator: ^7.1.0

flutter:
  uses-material-design: true
